name: CI

on:
  push:
    branches:
      - 'feature/*' # Trigger on pushes to any branch starting with 'feature/'

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          npm test
          echo Add other actions to build,
          echo test, and deploy your project.
